In [1]:
dictone = {
			"id":1,
			"code":"3314",
			"name":"中铁国际",
			"crate01":"+11.23%",
			"crate02":"20%",
			"crate03":28,
			"hight":56.8,
			"hightDate":"2018-02-23"
		}
print(dictone)

{'id': 1, 'code': '3314', 'name': '中铁国际', 'crate01': '+11.23%', 'crate02': '20%', 'crate03': 28, 'hight': 56.8, 'hightDate': '2018-02-23'}


In [3]:
for i in dictone:   # 取出的时key
    print(i,dictone[i])
    

id 1
code 3314
name 中铁国际
crate01 +11.23%
crate02 20%
crate03 28
hight 56.8
hightDate 2018-02-23


In [6]:
for m in dictone.items():
    print(m)

('id', 1)
('code', '3314')
('name', '中铁国际')
('crate01', '+11.23%')
('crate02', '20%')
('crate03', 28)
('hight', 56.8)
('hightDate', '2018-02-23')


In [8]:
for m,n in dictone.items():
    print(m,n)

id 1
code 3314
name 中铁国际
crate01 +11.23%
crate02 20%
crate03 28
hight 56.8
hightDate 2018-02-23


In [10]:
dictone[0]  # 字典不可以用索引取值，无序的

KeyError: '0'

In [2]:
import numpy as np
import pandas as pd
arr2 = np.arange(20).reshape(4, 5)
print(arr2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [4]:
df = pd.DataFrame(arr2)
print(df,type(df))


    0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19 <class 'pandas.core.frame.DataFrame'>


In [8]:
df.reshape（2，2，5）

SyntaxError: invalid character in identifier (<ipython-input-8-39c5089826fc>, line 1)

In [10]:
arr_1 = arr2.reshape(2,2,5) 
print(arr_1)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]


In [11]:
arr_1.T

array([[[ 0, 10],
        [ 5, 15]],

       [[ 1, 11],
        [ 6, 16]],

       [[ 2, 12],
        [ 7, 17]],

       [[ 3, 13],
        [ 8, 18]],

       [[ 4, 14],
        [ 9, 19]]])

In [12]:
arr_1.transpose(1,0,2)

array([[[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14]],

       [[ 5,  6,  7,  8,  9],
        [15, 16, 17, 18, 19]]])

In [13]:
arr_1.transpose(0,2,1)

array([[[ 0,  5],
        [ 1,  6],
        [ 2,  7],
        [ 3,  8],
        [ 4,  9]],

       [[10, 15],
        [11, 16],
        [12, 17],
        [13, 18],
        [14, 19]]])

In [14]:
arr_1.reshape(2,5,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [1]:
import numpy as np
import pandas as pd

In [26]:
np1 = np.arange(12).reshape(3,4)
np1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
print(np1.shape)
type(np1)

(3, 4)


numpy.ndarray

In [28]:
np1.T   # >>>  transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [29]:
np1.transpose()  # (1,0)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [31]:
np1.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [32]:
np1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
np1.reshape(2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [36]:
np1.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [33]:
np2=np.arange(6,24,2).reshape(3,3)
np2

array([[ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [19]:
np1.stack(np2)

AttributeError: 'numpy.ndarray' object has no attribute 'stack'