In [24]:
# 练习

In [25]:
import numpy as np

In [26]:
filename = 'presidential_polls.csv'

In [27]:
with open(filename,'r') as f:
    first_col = f.readline()[:-1]

In [28]:
print(first_col)

cycle,branch,type,matchup,forecastdate,state,startdate,enddate,pollster,grade,samplesize,population,poll_wt,rawpoll_clinton,rawpoll_trump,rawpoll_johnson,rawpoll_mcmullin,adjpoll_clinton,adjpoll_trump,adjpoll_johnson,adjpoll_mcmullin,multiversions,url,poll_id,question_id,createddate,timestamp


In [29]:
all_col_name_list = first_col.split(',')

In [30]:
usecols_list = ['matchup','adjpoll_clinton','adjpoll_trump','adjpoll_johnson']

In [31]:
usecols_index_list = [all_col_name_list.index(col_name) for col_name in usecols_list]

In [32]:
print(usecols_index_list)

[3, 17, 18, 19]


In [33]:
# 读数据  np.genfromtxt
data_arr = np.genfromtxt(filename,delimiter=',',dtype=str,usecols=usecols_index_list)

In [34]:
print(data_arr)   # 如何全部显示 ...

[['matchup' 'adjpoll_clinton' 'adjpoll_trump' 'adjpoll_johnson']
 ['Clinton vs. Trump vs. Johnson' '42.6414' '40.86509' '5.675099']
 ['Clinton vs. Trump vs. Johnson' '43.29659' '44.72984' '3.401513']
 ...
 ['Clinton vs. Trump vs. Johnson' '45.9713' '39.97518' '']
 ['Clinton vs. Trump vs. Johnson' '45.2939' '46.66175' '1.596946']
 ['Clinton vs. Trump vs. Johnson' '31.62721' '44.65947' '']]


In [35]:
alldata_array = data_arr[1:,1:]

In [36]:
print(alldata_array)

[['42.6414' '40.86509' '5.675099']
 ['43.29659' '44.72984' '3.401513']
 ['46.29779' '40.72604' '6.401513']
 ...
 ['45.9713' '39.97518' '']
 ['45.2939' '46.66175' '1.596946']
 ['31.62721' '44.65947' '']]


In [38]:
newall_data_arr = np.where(alldata_array == '','0',alldata_array)    # 数据清洗

print(newall_data_arr)

[['42.6414' '40.86509' '5.675099']
 ['43.29659' '44.72984' '3.401513']
 ['46.29779' '40.72604' '6.401513']
 ...
 ['45.9713' '39.97518' '0']
 ['45.2939' '46.66175' '1.596946']
 ['31.62721' '44.65947' '0']]


In [39]:
newall_data_arr = newall_data_arr.astype(np.float64)    # 已经可以用了
print(newall_data_arr)

[[42.6414   40.86509   5.675099]
 [43.29659  44.72984   3.401513]
 [46.29779  40.72604   6.401513]
 ...
 [45.9713   39.97518   0.      ]
 [45.2939   46.66175   1.596946]
 [31.62721  44.65947   0.      ]]


In [40]:
col_data = data_arr[0,1:]
print(col_data)

['adjpoll_clinton' 'adjpoll_trump' 'adjpoll_johnson']


In [41]:
print("{}:{}".format(col_data[0],np.sum(newall_data_arr[:,0])))
print("{}:{}".format(col_data[1],np.sum(newall_data_arr[:,1])))
print("{}:{}".format(col_data[2],np.sum(newall_data_arr[:,2])))

adjpoll_clinton:440402.87625999993
adjpoll_trump:430409.648269
adjpoll_johnson:31131.2616846


In [2]:
import numpy as np
import pandas as pd

In [3]:
file_name = 'class.csv'

In [52]:
# with open(file_name,'rb') as f:
#     fi_col = f.readline()[:-1].split(",")
# print(fi_col)

TypeError: a bytes-like object is required, not 'str'

In [4]:
filename1 = 'class_name.xlsx'

In [5]:
df = pd.read_excel('class_name.xlsx')
print(df)

     list    name    age haha
0   325.0  rewrtt  232.0  122
1     NaN  rewrtt  233.0  123
2    45.0  rewrtt  234.0  124
3    46.0       0    0.0  125
4    47.0  rewrtt  236.0   ""
5    48.0       6  237.0  127
6    49.0  rewrtt  238.0  128
7    50.0  rewrtt    NaN  NaN
8    51.0  rewrtt  240.0  130
9    52.0  rewrtt  241.0  131
10   53.0  rewrtt  242.0  132
11   54.0  rewrtt  243.0  133
12   55.0  rewrtt  244.0  134


In [ ]:
# newall_arr1 = np.where(df == "",0,df)     # ?????,这是numpy的
newall_arr1 = pd.where(df == "",0,df)
print(newall_arr1)

In [6]:
# dataarrall = np.genfromtxt(file_name, delimiter=',',dtype = str)    # 有编码问题，怎么解决？？？
df = pd.read_excel('class.csv')    # 读表格数据  空格读出结果为NaN   读 .csv 和 读 .xlsx 一样
print(df)                          # ""读入还是显示"" ，这三个不会处理它

     list    name    age   haha
0   325.0  rewrtt  232.0  122.0
1     NaN  rewrtt  233.0  123.0
2    45.0  rewrtt  234.0  124.0
3    46.0       0    0.0  125.0
4    47.0  rewrtt  236.0    NaN
5    48.0       6  237.0  127.0
6    49.0  rewrtt  238.0  128.0
7    50.0  rewrtt    NaN    NaN
8    51.0  rewrtt  240.0  130.0
9    52.0  rewrtt  241.0  131.0
10   53.0  rewrtt  242.0  132.0
11   54.0  rewrtt  243.0  133.0
12   55.0  rewrtt  244.0  134.0


In [18]:
df1 = df.loc[0,'name':'haha']   # 按索引取值，取一行，则为Series对象
print(df1)
print(type(df1))
for i in df1:
    print(i)

name    rewrtt
age        232
haha       122
Name: 0, dtype: object
<class 'pandas.core.series.Series'>
rewrtt
232.0
122.0


In [13]:
df2 = df[['age','haha']]  # 取出指定列的数据,列表
print(df2)

      age   haha
0   232.0  122.0
1   233.0  123.0
2   234.0  124.0
3     0.0  125.0
4   236.0    NaN
5   237.0  127.0
6   238.0  128.0
7     NaN    NaN
8   240.0  130.0
9   241.0  131.0
10  242.0  132.0
11  243.0  133.0
12  244.0  134.0


In [23]:
print(df2.sum())   # 同下
print(np.sum(df2))
print(type(df2.sum()))
for i in np.sum(df2):
    print(i)

age     2620.0
haha    1409.0
dtype: float64
age     2620.0
haha    1409.0
dtype: float64
<class 'pandas.core.series.Series'>
2620.0
1409.0


In [20]:
ser2 = df2.stack()    
print(ser2)
print(type(ser2))

0   age     232.0
    haha    122.0
1   age     233.0
    haha    123.0
2   age     234.0
    haha    124.0
3   age       0.0
    haha    125.0
4   age     236.0
5   age     237.0
    haha    127.0
6   age     238.0
    haha    128.0
8   age     240.0
    haha    130.0
9   age     241.0
    haha    131.0
10  age     242.0
    haha    132.0
11  age     243.0
    haha    133.0
12  age     244.0
    haha    134.0
dtype: float64
<class 'pandas.core.series.Series'>
